export const handleError = async (e: unknown) => {
  throw e;
};
